export enum APP_ROUTES {
  VISION = 'vision',
  EXPENSES = 'expenses',
  ASSETS = 'assets',
  DASHBOARD = 'dashboard',
}

export enum COLLECTIONS {
  YEARLY_EXPANSES = 'YEARLY_EXPANSES',
  MONTHLY_EXPANSES = 'MONTHLY_EXPANSES',
  INCOME = 'INCOME',
  CATEGORIES = 'CATEGORIES',
  DETAILED_EXPENSES = 'DETAILED_EXPENSES',
  ASSETS = 'ASSETS',
}
