export enum APP_ROUTES {
  VISION = 'vision',
  EXPENSES = 'expenses',
  ASSETS = 'assets',
  DASHBOARD = 'dashboard',
  LOGIN = 'login',
}

export enum COLLECTIONS {
  YEARLY_EXPENSES = 'YEARLY_EXPENSES',
  MONTHLY_EXPENSES = 'MONTHLY_EXPENSES',
  INCOME = 'INCOME',
  CATEGORIES = 'CATEGORIES',
  DETAILED_EXPENSES = 'DETAILED_EXPENSES',
  ASSETS = 'ASSETS',
}
